package com.xinto.mauth.core.otp.parser

enum class OtpUriParserError {
    ERROR_INVALID_PROTOCOL,
    ERROR_INVALID_TYPE,
    ERROR_INVALID_ALGORITHM,
    ERROR_INVALID_DIGITS,
    ERROR_INVALID_PERIOD,
    ERROR_INVALID_COUNTER,
    ERROR_MISSING_LABEL,
    ERROR_MISSING_SECRET,
    ERROR_MISSING_COUNTER,
}
