package com.xinto.mauth.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightMothPurple = lightColorScheme(
    primary = Color(0xFF8A4485),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD7F5),
    onPrimaryContainer = Color(0xFF380038),
    secondary = Color(0xFF6D5869),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF7DAEF),
    onSecondaryContainer = Color(0xFF271624),
    tertiary = Color(0xFF825345),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBD1),
    onTertiaryContainer = Color(0xFF321208),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color(0xFFFFFFFF),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1E1A1D),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1E1A1D),
    surfaceVariant = Color(0xFFEEDEE7),
    onSurfaceVariant = Color(0xFF4E444B),
    outline = Color(0xFF80747C),
    inverseOnSurface = Color(0xFFF8EEF2),
    inverseSurface = Color(0xFF342F32),
    inversePrimary = Color(0xFFFFABF3),
    surfaceTint = Color(0xFF8A4485),
    outlineVariant = Color(0xFFD1C2CB),
    scrim = Color(0xFF000000),
)

val DarkMothPurple = darkColorScheme(
    primary = Color(0xFFFFABF3),
    onPrimary = Color(0xFF551353),
    primaryContainer = Color(0xFF6F2C6B),
    onPrimaryContainer = Color(0xFFFFD7F5),
    secondary = Color(0xFFDABFD2),
    onSecondary = Color(0xFF3D2B3A),
    secondaryContainer = Color(0xFF554151),
    onSecondaryContainer = Color(0xFFF7DAEF),
    tertiary = Color(0xFFF5B8A7),
    onTertiary = Color(0xFF4C261B),
    tertiaryContainer = Color(0xFF663C2F),
    onTertiaryContainer = Color(0xFFFFDBD1),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1E1A1D),
    onBackground = Color(0xFFE9E0E4),
    surface = Color(0xFF1E1A1D),
    onSurface = Color(0xFFE9E0E4),
    surfaceVariant = Color(0xFF4E444B),
    onSurfaceVariant = Color(0xFFD1C2CB),
    outline = Color(0xFF9A8D95),
    inverseOnSurface = Color(0xFF1E1A1D),
    inverseSurface = Color(0xFFE9E0E4),
    inversePrimary = Color(0xFF8A4485),
    surfaceTint = Color(0xFFFFABF3),
    outlineVariant = Color(0xFF4E444B),
    scrim = Color(0xFF000000),
)

val MothPurple = Color(0xFF420042)